### PR TITLE
Post v0.4 release updates

### PR DESCRIPTION
**Pull request by ewels**
Hi all,

This PR is a suggestion only - feel free to leave open or to close/ignore. I'd like for your fork to stay as close to mine as possible to avoid drift again if we can, the best way to do that is with small and frequent PRs.

This has quite a lot of files / changes in it, but most of those are documentation and cleanup (removal of dead module files and so on). There are a few subtle bugfixes hidden in there too.

Phil

### CODE REVIEW

**Comment by s-andrews** [comment]
No problem.  We'd like to stay as close to upstream as possible.  We've got a few commits to push back too - mostly just cleaning up  modules.  The BSSeq stuff needs looking at as there are so many variants for processing different kits that we need to deal with that in a more flexible way.  We've done a bit to sort this out but need to do more.

**Comment by ewels** [comment]
Great 👍  Yes, I was a bit cheeky and already pulled your changes into the main branch: https://github.com/ewels/clusterflow/pull/108

Phil

**Comment by s-andrews** [comment]
Ha!  That explains why it didn't find anything when I tried to put a  
pull request toghether!

Simon.

Quoting Phil Ewels <notifications@github.com>:

**Comment by ewels** [comment]
Sorry! The changes looked fairly innocuous so I thought I'd just go ahead and do it myself rather than bothering you.. Will ask or at least ping you next time :)

**Comment by s-andrews** [comment]
It's fine. Help yourself!

On 5 Oct 2016 7:54 a.m., Phil Ewels <notifications@github.com> wrote:

Sorry! The changes looked fairly innocuous so I thought I'd just go ahead and do it myself rather than bothering you.. Will ask or at least ping you next time :)

**Pull request merged**
