### PR TITLE
Reverse PR - bringing BI back to v0.4devel

### PR DESCRIPTION
**Pull request by ewels**
Ok, now it's time to bring you back up to date with the main Cluster Flow repo..

This is quite a large pull request!

### CODE REVIEW

**Comment by ewels** [comment]
Ah, only 37,683 lines of new code for you to review, should be possible over a quick cup of coffee..

This is where the magic happens though - I think I'm right in saying that because the git history on the main repo includes your commits after I merged them, git should know how to apply this huge update. So it should merge without conflicts and magically bring your fork back up to date with the main repo.

**Comment by ewels** [comment]
@s-andrews and @FelixKrueger - I'll leave this PR open for you to merge, as it's your repository and I don't want to trample on it. But I think it should be good to go.

Once you're up to date, we can look at doing any final updates that you want (you mentioned something about filenames?) then I can push the v0.4 release next week.

**Comment by s-andrews** [comment]
OK, I've merged it.  I'll do a separate checkout on our cluster to test this
as it's probably going to break something.

Simon.

From:  Phil Ewels <notifications@github.com>
Reply-To:  s-andrews/clusterflow
<reply+007c7ae30a704205ecf1105b7b841887399a3b93cfcc987f92cf00000001137297179
2a169ce09841c32@reply.github.com>
Date:  Friday, 10 June 2016 at 15:56
To:  s-andrews/clusterflow <clusterflow@noreply.github.com>
Cc:  Simon Andrews <simon@proteo.me.uk>, Mention
<mention@noreply.github.com>
Subject:  Re: [s-andrews/clusterflow] Reverse PR - bringing BI back to
v0.4devel (#3)


@s-andrews <https://github.com/s-andrews>  and @FelixKrueger
<https://github.com/FelixKrueger>  - I'll leave this PR open for you to
merge, as it's your repository and I don't want to trample on it. But I
think it should be good to go.

Once you're up to date, we can look at doing any final updates that you want
(you mentioned something about filenames?) then I can push the v0.4 release
next week.


You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/s-andrews/clusterflow/pull/3#issuecomment-225205281> ,
or mute the thread 
<https://github.com/notifications/unsubscribe/AHx642DvykvlDLmYeeh2qPVH_Dyeb3
X7ks5qKXsXgaJpZM4IzBwj> .

**Comment by ewels** [comment]
Awesome! Ah, such simplicity:
image

I await the inevitable bug reports..

**Pull request merged**
